language: perl
perl:
  - "5.26"
  - "5.24"
  - "5.22"
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
#  - "5.8" # We are currently not 5.8 safe due to the Regexp::Common dependency of Mail::DMARC which requires at least 5.10

#branches:
#  only:
#    - releases

matrix:
  include:
    - perl: 5.26
      env: COVERAGE=1

before_install:
   - git config --global user.name "TravisCI"
   - git clone git://github.com/travis-perl/helpers ~/travis-perl-helpers
   - source ~/travis-perl-helpers/init
   - build-perl
   - perl -V
   - cpanm -n Devel::Cover::Report::Coveralls
   - coverage-setup

install:
    - cpanm --quiet --notest --skip-satisfied Dist::Zilla
    - cpanm --quiet --notest Module::Install
    - cpanm --quiet --notest Mail::SPF --install-args="--install-path sbin=/tmp"
    - cpanm --quiet --notest Test::More Test::File::Contents Test::Perl::Critic
    - cpanm --quiet --notest List::MoreUtils::XS List::MoreUtils
    - cpanm --quiet --notest Test::CheckManifest Test::Pod::Coverage Test::Pod
    - cpanm --quiet --notest Cwd Email::Date::Format Email::Simple
    - cpanm --quiet --notest English IO::Socket JSON Mail::DKIM::Verifier Mail::DKIM Mail::AuthenticationResults
    - cpanm --quiet --notest MIME::Base64 Module::Load Module::Loaded
    - cpanm --quiet --notest Net::DNS
    - cpanm --quiet --notest Net::DNS::Resolver::Mock
    - cpanm --quiet --notest Net::IP Net::Server
    - cpanm --quiet --notest Pod::Usage Proc::ProcessTable Socket Sys::Hostname Sys::Syslog
    - cpanm --quiet --notest git://github.com/fastmailops/mail-dmarc.git@fastmail
    - cpanm --quiet --notest Dist::Zilla::Plugin::OurPkgVersion || cpanm --quiet --notest Dist::Zilla::Plugin::OurPkgVersion@0.14
    - dzil authordeps --missing | cpanm --quiet --notest
    - dzil listdeps --missing | cpanm --quiet --notest
    - cpan-install --coverage

script:
   - dzil test

after_success:
  - coverage-report

